### ISSUE TITLE
support at least some inline html

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#13]
... to be rendered as such after parsing. Specifically:
```
<i></i>
&nbsp;
<br/>
```
I'll be adding `<i></i>` pairs to some of the sections of this piece and I was experimenting with `&nbsp;` and `<br/>` for section 17.

**Comment by cqx931** [comment]
This is supported in the latest PR https://github.com/shadoof/rtwtr/pull/17, please check.

**Comment by cqx931** [comment]
Can this be closed? @shadoof

**Comment by shadoof** [comment]
Yes. Let's close this and revisit if necessary via #12
