### ISSUE TITLE
serious bug in section 12

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#19]
must be an infinite loop: everything stops, I can even open the console on Chrome.
Reproduce by:
- navigating to section 12
- mouseover the sentence beginning: "One may disregard the wheels ..."

(I haven't made any changes to the a_ or b_files so you can get a clear run at this one.

**Comment by cqx931** [comment]
That's also the case for the first sentence in section 7, I will work on this today.

**Comment by cqx931** [comment]
Also for first sentence in section 17

**Comment by shadoof** [comment]
That's new to me. Was ok before ...


On May 20, 2020 at 10:07:34 AM, cqx931 (notifications@github.com) wrote:

Also for first sentence in section 17

**Comment by cqx931** [comment]
fixed
