### ISSUE TITLE
when there is no actual text to replace anything in the `a_file`

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#22]
in section 2 and 11 _empty_ units are set up to in the `b_file` to correspond with _extra_ text units in the `a_file`.
The animation currently goes to onHover_opcity and then nothing happens.
If there are no `b_file` spans at all then we need to have it theses text fade to fade_opacity after PHASE1_PHASE2_DELAY.

**Comment by cqx931** [comment]
the current issue is that these units won't enter phase2 at all because there is no shared units to trigger the mouseover event. Do we have any other cases in the text where there is no shared units between one a b text pair?

**Comment by shadoof** [comment]
I think section 2 and 11 are the only places in the current text. But yes, needs to be part of the general plan. I imagine that this could be handled by testing to see if there are any non-empty strings in the corresponding b_unit and if (b_unit is empty) then: so long as mouse is still within the a_unit, then behave exactly as if the pointer is over a shared span, i.e. fade the a_unit out to fade_opacity after the PHASE1_PHASE2_DELAY.

**Comment by cqx931** [comment]
fixed https://github.com/shadoof/rtwtr/pull/33/commits/127961af760329eeb1665de46582c93e4ef706ab
