### ISSUE TITLE
text marked with <ub></ub> seems to require at least one piece of "tb" punctuation

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#26]
Issue can be reproduced by removing the "." from the end of the last unit in section 17.

We should be able to have units marked with `<ub>` tags without any need for <tb/> or any other conventional thought-break punctuation.

**Comment by cqx931** [comment]
I'm not sure whether this is really related to the punctuation marks...but after I cleaned up the code, in the latest commit, "." can be removed from the end of the last unit and the <ub> does apply correctly to both a and b divs.

Please let me know if you notice any further issues on this.

**Comment by shadoof** [comment]
Closing. Will reopen if necessary ...
