### ISSUE TITLE
units that have no shared spans have no way to trigger phase 2

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#27]
This is very similar if not the same issue as #22 but I've made a separate issue since conditions are a little different.

Example at the end of section 17.

**Comment by cqx931** [comment]
Fixed. https://github.com/shadoof/rtwtr/pull/33/commits/127961af760329eeb1665de46582c93e4ef706ab

**Comment by shadoof** [comment]
Broken again in `49b5fb7` - 'signature' at end of section 17. (Not sure if there are other examples in the text, but there could be, in principle.)

**Comment by shadoof** [comment]
I think you fixed this. Close?

**Comment by cqx931** [comment]
close
