### ISSUE TITLE
section navigation widget

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#28]
easy?

**Comment by cqx931** [comment]
@shadoof 
Could you remind me of the design you have in mind? I think you briefly mentioned that you want a dropdown menu with all the page numbers and the arrow keys being able to go to prev page and next page. 
Something like this?
<<   7   >>

**Comment by shadoof** [comment]
I do like the design you suggest with the `<<>>` chevrons. I was just thinking left justified above the text separated by one blank line.

**Comment by cqx931** [comment]
widget added https://github.com/shadoof/rtwtr/pull/33/commits/181f0c5bb3caf588530b59223ca6a297603c2a64
please check and let me know if there is more style tweaks you want to make.

**Comment by shadoof** [comment]
Thanks for this Sally. Could we try two things:
- Slightly larger font size (and to double-check: is this Garamond with same set up as for text?)
- Try positioning a little lower (more top margin) and over about the left margin area (chiefly because I don't much like how the drop down intrudes on the text and so both the menu and the text are difficult to read)

**Comment by shadoof** [comment]
Also the "<<" and ">>" of the widget should not appear to be active when hovered.

**Comment by cqx931** [comment]
How about this? The font size is 20px for the menu, while the main text is 24px. 24px would be a bit too big I think.
![Screenshot 2020-05-23 at 5 51 59 PM](https://user-images.githubusercontent.com/3056154/82741241-209d9780-9d1e-11ea-8d24-36d2fdacab64.png)

**Comment by cqx931** [comment]
oh the "<<" and ">>" are supposed to be "previous page" and "next page" buttons(which I forgot to add for the current commit). Do we still want that function? They can also just be purely decorative, if so, I will remove the on hover effect.

**Comment by shadoof** [comment]
look of the previous comment seems good to me and sorry! yes: I think the previous and next behaviors active on "<<" and ">>" are just as they should be! My bad.

**Comment by cqx931** [comment]
Please check https://github.com/shadoof/rtwtr/pull/36/commits/ec0d56cc25d2e4a198680dbc955843cf4a6ceefc

**Comment by shadoof** [comment]
for tweaking, see #39
