### ISSUE TITLE
enhanced phase 2 (i.e. when B_file showing) animation

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#31]
Let's forget about trying to do this with mouseover ! (when mouse moves over non-shared parts)

The non-shared `B_unit` parts should simply transition to `B_unit` default opacity after a delay of about 1.5 to 2 seconds. Easy, right?

--

	} else if pointer moves over non-shared parts of the B_unit: {
		All of the B_unit transitions quickly to default_opacity;

At the moment, if the cursor stays within the B-unit but moves off a shared span onto a non-shared span, nothing happens (shared spans stay b_default_opacity non-shared spans stay b_onHover_opcity).

**Comment by cqx931** [comment]
done
