### ISSUE TITLE
postioning problems

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#37]
Enter the first sentence of section 1 so as to be able to hover over one of the _later_ potential anchor points (e.g. 'in our surroundings'). This produces an overlap of the end of the last line of the B file text and the beginning of the 2nd A file sentence.

**Comment by cqx931** [comment]
This is the sentence you are talking about, right? I don't see the overlap on my end
![Screenshot 2020-05-24 at 4 46 16 PM](https://user-images.githubusercontent.com/3056154/82764615-2490ee80-9dde-11ea-96ff-af5ff49f24c4.png)

**Comment by shadoof** [comment]
In haste before shutting down to say yes. I have absolutely no explanation at the moment:

My Chrome:



My Safari:



. .  .   .     .       .         .                .
John Cayley
Professor and Chair of Literary Arts
iPhone: +1 (401) 368 3002
email: john_cayley@brown.edu
personal zoom: https://brown.zoom.us/my/johncayley/
. .  .   .     .       .         .                .

On May 24, 2020 at 4:47:33 PM, cqx931 (notifications@github.com) wrote:

This is the sentence you are talking about, right? I don't see the overlap on my end

**Comment by cqx931** [comment]
@shadoof Could you send the screenshots again through github? There are some issues with images when you post from emails and I can't see them.

**Comment by shadoof** [comment]
<img width="821" alt="Screen Shot 2020-05-24 at 10 54 18 PM" src="https://user-images.githubusercontent.com/1051808/82954143-1f68a680-9f7a-11ea-9528-492fbf9188a8.png">

**Comment by shadoof** [comment]
<img width="857" alt="Screen Shot 2020-05-24 at 10 57 26 PM" src="https://user-images.githubusercontent.com/1051808/82954165-2b546880-9f7a-11ea-8d01-af0d3c9dd7ff.png">

**Comment by shadoof** [comment]
First is Chrome; second Safari. (And I noticed something else weird. More when I can but perhaps not this evening.)

**Comment by cqx931** [comment]
The font seems to look differently in Safari. And it also looks different compared to what I can see for my chrome. Shall we try to load the font from our own font file instead of calling the ones installed in the system? That should be make it more consistent across devices. 

Ideally, if you locate the Garamond font file on your computer and upload it to github that would be the best. I can take care of the rest to use that font file for the page.

**Comment by shadoof** [comment]
Yes: fonts are part of the problem. The one I like is weirdly placed in my system, which might be the problem. Here it is.
[Garamond.zip](https://github.com/shadoof/rtwtr/files/4688461/Garamond.zip)

**Comment by shadoof** [comment]
And here are second and third choices as in the edited style.css file.
[ACaslonPro.zip](https://github.com/shadoof/rtwtr/files/4688489/ACaslonPro.zip)
[AGaramondPro.zip](https://github.com/shadoof/rtwtr/files/4688497/AGaramondPro.zip)

**Comment by shadoof** [comment]
Found another instance of the end-of-sentence overlap error in section 6 (screenshot below). Double-checking that you know this only happens when mousing over particular shared spans before phase 2, in this case "inaccessible to".
<img width="971" alt="Screen Shot 2020-05-27 at 9 18 04 AM" src="https://user-images.githubusercontent.com/1051808/83023775-60ed6600-9ffb-11ea-870e-b4945223f2a1.png">

**Comment by cqx931** [comment]
Shall we just include the first Garamond fonts? As long as we import our own font, it's not necessary to provide second and third custom fonts to fall back to.

And yes now I can finally reproduce this issue, let me check.

**Comment by shadoof** [comment]
Sure. So long as it's reliable, that would be great to just use the cut of Garamond that I like.

**Comment by cqx931** [comment]
The second issue is caused by the italic style in the original <a> unit, which fails to be passed to beforeAnchorA in Overlay.

**Comment by shadoof** [comment]
Right. Can you still not reproduce the same kind of overlap for Section 1, sentence 1? I get it with *most* but not all of the hovered shared spans in the latter part of the sentence.

Could it be something to do with quotation marks? The accented letter in "Vilém"?

**Comment by cqx931** [comment]
@shadoof I can reproduce the issue now. It's more about the text length difference between what we have in the report and the real situation.

Please check https://github.com/shadoof/rtwtr/pull/43

The issue should be fixed now.

**Comment by shadoof** [comment]
I hope you saw my commit `910b149` re: Chrome and Safari dealing with relative path names differently! Anyway, the following may be something only solvable by a "This looks better in Chrome" message but even after getting the fonts to be packed into the webapp, Safari – but _not_ Chrome – still does this with the 2nd sentence of Section 17 (and perhaps others):
<img width="861" alt="Screen Shot 2020-05-28 at 9 31 13 AM" src="https://user-images.githubusercontent.com/1051808/83147855-35837d80-a0c6-11ea-995c-80dd2665bdf5.png">

**Comment by cqx931** [comment]
This seems to be caused by trailing space differences across browsers. I will see what I can do about it.

**Comment by cqx931** [comment]
@shadoof please check https://github.com/shadoof/rtwtr/pull/47. This will fix the issue for me.

**Comment by shadoof** [comment]
Yes: fixed for me too in Safari and Chrome. Keeping this last issue open as I continue to test ...

**Comment by shadoof** [comment]
I take it back – may not have updated properly: Both browser now positioning that B unit the same way!

**Comment by shadoof** [comment]
Closing this since we are about to release the DR version.
