### ISSUE TITLE
reorganize for deployment (folder structure, assets etc.)

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#41]

**Comment by cqx931** [comment]
Do you still need the current index file? I can either replace it with the one we have in the test folder instead.

**Comment by shadoof** [comment]
Would you mind moving it to an "InitialSketch" folder?

**Comment by cqx931** [comment]
Cool, will do.

**Comment by cqx931** [comment]
@shadoof And the rtwtr.html file?

**Comment by cqx931** [comment]
I did a first-round clean up in the latest PR. Let me know if there is any other changes you want to make. https://github.com/shadoof/rtwtr/pull/42

**Comment by shadoof** [comment]
Made some. Closing this in next commit.
