### ISSUE TITLE
the signature at end of section 17

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#44]
Made a separate issue for this, since #29 is only one possible solution and I'd be happy just to hack this for the DR publication.

I used `&nbsp;` so that the signatures in both A and B would be spaced out on their lines as I wanted for a fixed width font, which I'd also like to use for aesthetic reasons: "Courier New" would be fine. Thus (although GitHub doesn't necessarily render in Courier New):

```
-John
+Vilém
      -Cay
      +F
        l
        +uss
            e
            -y
            +r
2019–20
_____________

-Vilém
+John
     -F
     +Cay
         l
         -uss
          e
          -r
          +y
1983–4
```

**Comment by cqx931** [comment]
Please check https://github.com/shadoof/rtwtr/pull/45. You can also fine-tweak the styles at https://github.com/shadoof/rtwtr/pull/45/commits/937b69019c830f32de81ec78ba70425e5e475abc#diff-da232d78aa810382f2dcdceae308ff8eR163

**Comment by shadoof** [comment]
Very cool! ... except. Not working when the B unit fades in:
<img width="323" alt="Screen Shot 2020-05-27 at 3 41 53 PM" src="https://user-images.githubusercontent.com/1051808/83065050-cf005000-a030-11ea-8358-6bdf1a14cc0c.png">
--
<img width="192" alt="Screen Shot 2020-05-27 at 3 41 41 PM" src="https://user-images.githubusercontent.com/1051808/83065071-d889b800-a030-11ea-81bf-89cbec1adf39.png">

**Comment by cqx931** [comment]
@shadoof 
Ops, I forgot to add it also to the overlay. This should do the hack!
https://github.com/shadoof/rtwtr/pull/46/commits/156e90082fb54f2b183b0d98a6218ac716db18d1

**Comment by shadoof** [comment]
Yay! Closing this. I guess that now it's just, "Test, test, test." as ProfDr Daniel days ;) and close the last "Needed for DR publication" issue on Thursday.
