### ISSUE TITLE
viajsdiff branch: lines moving down to make space when <verse> makes this undesirable

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#60]
reproduce with `a_` and `b_via_test.txt` in place, then hover over "the" in first line:

If something is <verse> we should strenuously avoid shifting replacement text up or down: should only happen in extreme cases, and if it does, there should be word wrapping to indicate why it is happening

**Comment by cqx931** [comment]
issues with `animateSurroundings()`  after:
https://github.com/shadoof/rtwtr/blob/viajsdiff/js/animation.js#L203

**Comment by cqx931** [comment]
The issues I see are following:
1. The current context report doesn't translate `<br>` to spaces, shall we integrate that? In this case, though it actually has enough place for the replacement text, the context analysis doesn't see it.
2. Shall we try to avoid 'lines moving down to make space' in verse mode? To me, this makes more sense in the normal context, while not so much for verses.
https://github.com/shadoof/rtwtr/pull/61/commits/1b719c601da63476f19ad7b42dc3ee0c63eccc48

**Comment by shadoof** [comment]
Hi Sally, Thanks for getting back to rtwtr. Here, I'm fielding more stupid crises ;) See below:

. .  .   .     .       .         .                .
John Cayley
Professor and Chair of Literary Arts, Brown University
iPhone: +1 (401) 368 3002
email: ***@***.***
personal zoom: https://brown.zoom.us/my/johncayley/
. .  .   .     .       .         .                .


On March 17, 2021 at 1:06:57 PM, cqx931 ***@***.***) wrote:

The issues I see are following:

The current context report doesn't translate 
to spaces, shall we integrate that? In this case, though it actually has enough place for the replacement text, the context analysis doesn't see it.
Yes, ultimately we much treat spaces as first class entities, real things, not white space. I'm inclined, for example, to be consistent in using Diff.wordDiffWithSpace() rather than wordDiff() (if I've remember those method names right).


Shall we try to avoid 'lines moving down to make space' in verse mode? To me, this makes more sense in the normal context, while not so much for verses.
Yes. There are extremely rare edge cases but we need not account for these in what we have for the moment.

In haste and all best,

John
