### ISSUE TITLE
viajsdiff branch, with via1.txt=afile and via2.txt=bfile, left-margin issue for text fading in

### ISSUE THREAD

**Issue by shadoof** [shadoof/rtwtr#63]
reproduced when hovering over final shared span in the second line:
when the text fades in the third line is indented and should not be
minor bug, but probably worth investigating

**Comment by cqx931** [comment]
fixed indent calculation for afteranchor when the line should just be left aligned without previous content.
https://github.com/cqx931/rtwtr/commit/bdeb8911de33949e3cc1c77966e2484c0f4106e7

**Comment by shadoof** [comment]
Closing, but there are still some positioning issues. That we will have to work through with the original Flusser/Cayley a and b files. Weirdly I have noticed – but cannot always reproduce reliably – positioning errors that happen the first time a text is replace but not subsequently. It's as if the correct positions are learned by the system and then not forgotten? Something to do with js and DOM (a)sync relations?
